- README.md
Add some basic usage information
> add readme with some basic usage information

- README.md
helps address #5 
this assumes that you will be using ~/theme_wrapper as the path for your workspace.
> local development with ddev

- scss/_colors.scss
- scss/style.scss
Creates `_colors.css` with values from legacy global variables and PSU Color Guide.  Converted any RGB values to hex for uniformity.  Team can discuss and refine further.
> prelim color values file for issue 12

- .gitignore
- css/style.css
- js/base/application.js
- js/psulib_base.global.js
- mix-manifest.json
- psulib_base.libraries.yml
- webpack.mix.js
I have added a convention for handling global javascripts in the base theme, javascripts added to `js/base/*.js` will get mixed into `js/application.js` which will get loaded by default when running this theme
> mix javascript

- psulib_base.info.yml
- templates/layout/page.html.twig
> added above_header region

- psulib_base.libraries.yml
Fixes JS errors thrown while logged out of site.
> add core/drupal and core/once as deps

- js/base/jumpmenu.js
Basic jump menu tool, please review
> Adding Jump Menu JS

- js/base/jumpmenu.js
Xiaoyu reminded me that currently the button just says 'Dropdown button' and this needs to be a different default, with configuration, so this adds that in
> Adding configurable menu button label

- components/breadcrumbs/breadcrumbs.scss
- components/breadcrumbs/breadcrumbs.twig
- psulib_base.theme
> preprocess breadcrumb, add page title, modify scss

- psulib_base.theme
- templates/views/views-view-table.html.twig
PR for 2 theme issues.  Fixing cache on breadcrumbs and adding `table-responsive` wrapper around views table displays.
> 91 breadcrumbs are being improperly cached

- components/header/header.component.yml
- components/header/header.scss
- components/header/header.twig
- psulib_base.info.yml
- templates/layout/page.html.twig
These changes will allow the hours block to be placed but there will likely need to be additional styles for the off canvas section and the header menus.
- Updated the header component to use new design layout. 
- Added offcanvas functionality for module
- Added addition regions to the header component (and theme) so we can place blocks more granularly
> 104 update header component

- components/alert_banner/alert_banner.js
- components/pagination/README.md
- components/sidebar_menu/README.md
- components/sidebar_menu/sidebar_menu.component.yml
- components/sidebar_menu/sidebar_menu.js
- components/sidebar_menu/sidebar_menu.scss
- components/sidebar_menu/sidebar_menu.twig
- mix-manifest.json
- templates/block/block--system-menu-block.html.twig
- templates/navigation/menu--sidebar-first.html.twig
To test this remove the menu--sidebar-first.html.twig template from the psul_theme and clear cache.  This should have not visual difference.
> 137 sdc port sidebar menu component to the base theme

- components/header/header.scss
- components/header/header.twig
> 148 header is not aligned with main content

- components/not_found/README.md
- components/not_found/not_found.component.yml
- components/not_found/not_found.scss
- components/not_found/not_found.twig
- mix-manifest.json
- package-lock.json
- templates/layout/page--403.html.twig
- templates/layout/page--404.html.twig
Adding component based on https://psu-flex-storybook.vercel.app/?path=/story/pages-error404--default.  Screenshots can be found below:
> 127 add 404403 page templates

- package-lock.json
Update dependencies with security issues.
> 169 update base theme dependencies

- components/header/header.scss
- components/header/src/header.js
- components/sidebar_menu/sidebar_menu.scss
- components/sidebar_menu/src/sidebar_menu.js
- templates/navigation/menu--nav-offcanvas.html.twig
- Adding template so menus in offcanvas use the sidebar menu component
- Removing duplicate styles and behaviors from the header related to the offcanvas menu
- Increasing clickable area of dropdown arrow to 44 x 30 pixels.
> 175 mobile navigation improvements

- templates/layout/region--sidebar-first.html.twig
copied code from: https://github.com/psu-libraries/psul-web/blob/1adc0642f68c0b1470bf166efdd2475b084054ad/web/themes/custom/psul_theme/templates/layout/region--sidebar-first.html.twig
> Port sidebar first template from psul_theme

- scss/components/file.scss
updating path for several icons so they are properly pointing at the bootstrap icons directory.
> Issue #191 - Fixing the file pages for 4 filetypes.

- mix-manifest.json
- package-lock.json
- psulib_base.info.yml
- scss/ck5style.scss
- webpack.mix.js
Add css to the WYSIWYG editor so the content looks like what it will look like when published.
> Issue #194 - Compiling and adding styles for ckeditor5.

- components/pagination/pagination.scss
- components/pagination/pagination.twig
- templates/navigation/pager.html.twig
- templates/views/views-mini-pager.html.twig
I also added a template to format the mini pager as well.
> Issue #193 - Adding pagination styles based on PSU Flex storybook.

- scss/_variables_bootstrap.scss
This should have no visible impact on the site but reduces the css loaded by ~6k.  I was hoping for more but I'm creating a PR because it isn't nothing.
> Issue #235 - Disabling some bootstrap scss options.

- components/icon/icon.component.yml
- package-lock.json
Minor fix that I missed in the previous PR.   This is to future proof the component.
> Issue #240 - Quoting the type value since that is required for D11.

- scss/components/general.scss
```html
<div class="item-list">
<h3>Library Guides</h3>
<ul class="list-unstyled">
<li><a href="https://guides.libraries.psu.edu/child-abuse-neglect" target="_blank">Child Abuse and Neglect</a></li>
</ul>
</div>
```
vs 
```html 
<div class="item-list">
<h3>Library Guides</h3>
<ul class="">
<li><a href="https://guides.libraries.psu.edu/child-abuse-neglect" target="_blank">Child Abuse and Neglect</a></li>
</ul>
</div>
```
> 242 style in generalscss is adding left margin to list unstyled

- components/content_with_toc/content_with_toc.twig
Changing TOC padding and flex direction on smaller screens.
https://github.com/user-attachments/assets/32b36406-8747-4037-a4f8-af9d4f2d5930
> Issue #246 - Updating toc behavior on smaller screens.

- js/validate-form.js
- psulib_base.libraries.yml
- psulib_base.theme
- scss/_variables_bootstrap.scss
- scss/base/_forms.scss
- scss/components/webform.scss
- templates/form/form-element.html.twig
There are a number of changes:
- Add icons for form validation.
- Adding basic styles to set border color to red if user enters invalid data on any form. 
- Updating form-element template to try to add invalid-feedback div
- Added JS library to trigger bootstrap form validation.
> 256 improve styles for invalid form

- components/news_cards/README.md
- components/news_cards/news_cards.component.yml
- components/news_cards/news_cards.scss
- components/news_cards/news_cards.twig
Creating a news card component to display news articles.  Based on https://psu-flex-storybook.vercel.app/?path=/story/core-composite-editorial-newscards--default
> 284 component news cards

- scss/base/_forms.scss
Removed left border from radius from search input.
> removed left border radius from input

- components/dynamic_hero/dynamic_hero.component.yml
- components/dynamic_hero/dynamic_hero.scss
- components/dynamic_hero/dynamic_hero.twig
- stories/psul-landing-page.stories.js
Adding a new component for the Dynamic Hero.  Currently, this does not support a bg image.  I will add that in a follow up issue.
- Go to http://localhost:6006/?path=/story/sdc-dynamic-hero--basic&args=background_gradient:dark
- You should see a new dynamic Hero component that mirrors https://psu-flex-storybook.vercel.app/?path=/story/core-composite-editorial-dynamichero--default&args=backgroundGradient:light;imageToggle:false;videoToggle:false
- Go to http://localhost:6006/?path=/story/psu-landing-page--basic 
- You should see the hero place in a new page mock up.
> 320 component dynamic hero

- components/card/card.component.yml
- components/card/card.scss
- components/card/card.twig
- components/icon/icon.component.yml
See commits for fixes.  
This is component variant is integrated with Drupal in https://github.com/psu-libraries/psul-web/pull/989.  It would be easiest to using that PR to test this.
> 381 add nav card variant to card component fixes
