psu-libraries/psulib_base

psulib_base.info.yml
psulib_base.theme
scss/base/_footer.scss
scss/base/_layout.scss
scss/style.scss
templates/block/social-media-links-platforms.html.twig
templates/layout/page.html.twig
templates/navigation/menu--footer.html.twig

* Switched to container-fluid in layout and set a max-width. 
* Adding 2 additional footer regions. Using bootstrap grid classes to change the layout.
* Adding logo to the footer (not a block but same logo as header)
* Updated the footer menu template to remove bootstrap dropdown functionality
* Adding template for social-media-links so we can us that module to add links to the footer. 
* Adding general footer styles
* Added `~` prefix to bootstrap imports to make it clearer that this is being pulled from node_modules.

17 basic theme footer

---

layouts/README.md
layouts/psul-one-column.html.twig
layouts/psul-two-column-33-66.html.twig
layouts/psul-two-column-50-50.html.twig
layouts/psul-two-column-66-33.html.twig
psulib_base.layouts.yml

Adding 3 layouts that use bootstrap classes.  On mobile the 66/main column is first in both the 33-66 and 66-33 templates.

Issue #59 - Adding 3 two column layouts based on bootstrap.

---

components/footer/footer.twig
components/header/header.scss
scss/_variables_bootstrap.scss
scss/base/_layout.scss
templates/block/block--system-branding-block.html.twig

Minor tweaks to the header to fix the following issues:
- Adding width and height attributes to header and footer logo to reduce layout shift
- Adjusting styles so prevent overflow on mobile header (shrinking PSU logo and changing flex)
- Decreasing font-size on nav actions to reduce likelihood of main nav wrapping.

122 decrease header logo on small screens prevent header overflow

---

scss/base/_layout.scss
templates/layout/page.html.twig

Video of this in action can be found here: https://teams.microsoft.com/l/message/19:ff313ec19e434a1198cb78c56f9cda4d@thread.tacv2/1722274094901?tenantId=7cf48d45-3ddb-4389-a9c1-c115526eb52e&groupId=19fa5341-d944-4d72-8d29-17587ea65671&parentMessageId=1722272085169&teamName=Drupal%20Migration&channelName=Drupal%20Team&createdTime=1722274094901&ngc=true
This makes the sidebars fixed width to help prevent overflow of the sidebar menu.

132 increase sidebar width on tablets

---

components/button/button.scss
components/header/header.component.yml
components/header/header.js
components/header/header.scss
components/header/header.twig
components/sidebar_menu/sidebar_menu.scss
mix-manifest.json
psulib_base.libraries.yml
scss/components/general.scss
scss/components/nav.scss
scss/style.scss

Porting header and main menu style changes from the base theme.  This also includes:
- Fix from https://github.com/orgs/psu-libraries/projects/29/views/4?sliceBy%5Bvalue%5D=Sprint+9+-+Release&pane=issue&itemId=73214201
- Webkit antialiasing fix to make fonts clearer
- First stab at cleaning up header styles
- Splitting nav into a separate library (some header styles should go in here)

138 port headermain nav styles to base theme

---

components/accordion/accordion.component.yml
components/accordion/accordion.scss
components/accordion/accordion.twig
mix-manifest.json
psulib_base.libraries.yml
scss/components/accordion.scss

This is related to https://github.com/psu-libraries/psul-web/tree/549-remove-accordion-component-from-psul_theme which removes the accordion styles from the sub theme and updates implementations of this on lib guides page.

62 sdc port accordion component to base theme

---

components/breadcrumbs/breadcrumbs.scss

Decrease the font-size on breadcrumbs to $font-size-sm.

Issue #147 - Decreasing font-size of breadcrumb.

---

components/header/header.js
templates/navigation/menu--main.html.twig

… with class.
There should be no visual change on this.  Porting https://github.com/psu-libraries/psul-web/blob/main/web/themes/custom/psul_theme/templates/navigation/menu--main.html.twig into the base theme.  Adjusted javascript to handle a class or an id for the main menu.
This should probably be included in component.

150 dropdown menu does not work with the base theme alone

---

components/contact_card/README.md
components/contact_card/contact_card.component.yml
components/contact_card/contact_card.scss
components/contact_card/contact_card.twig
mix-manifest.json

This can be tested by replacing `psul_theme:contact_card` with `psulib_base:contact_card` in `/psul_theme/templates/content/node--department--contact.html.twig` and `/psul_theme/templates/content/node--library--contact.html.twig`. This should have no visual changes.

Issue #136 - Porting contact card component from psul_theme.

---

assets/fonts/fonts.css
psulib_base.theme

- Documenting why font files are preloaded
- Preloading bold and italic font files (since they are used on almost every page)
- Removing `RobotoCondensed-Italic-VariableFont_wght.woff2` since we're not italicizing any menu links and the italic seem to work without the separate file.   This was being unnecessarily loaded on every single page.

217 update preloaded fonts

---

components/accordion/accordion.scss

After adding the flex display the accordion button looks correct again:

Issue #223 - Explicitly setting display on accordion buttons to flex.

---

components/content_with_toc/content_with_toc.twig
scss/_base.scss
scss/_mixins.scss
scss/base/_full_bleed.scss

Adding some basic styles to add full width background colors.  These should only be used on pages without sidebars.
The following classes can be added to divs to add the background color.
`full-bleed full-bleed--limestone-light`
`full-bleed full-bleed--slate-light`

232 add full bleed styles to allow background colors

---

components/contact_card/contact_card.component.yml
components/contact_card/contact_card.scss
components/contact_card/contact_card.twig

Reworked the contact card component so i can be used on the directory page.
- Add wrapper to the contact card so we can cleanly handle images and the chevron with stacked functionality. You can see different flex layouts below.
- Added new props to pass in images and linked_card setting.  
- Update and template and styles to make this work.
https://github.com/user-attachments/assets/c40dc02c-703a-431f-b1b4-844a0dc78304
We might need to do additional work with the images.
I tested this on the psul-web site by modifying `node--department--contact.html.twig` template to something like (the last 3 properties are new).  Then moving the Contact block from the sidebar to the main content. 
```twig
{% include 'psulib_base:contact_card' with {
title: label,
title_url: url,
subtitle: '',
address: …
```

237 add directory display variant to contact card

---

components/content_with_toc/content_with_toc.twig

The default offset for the scrollspy feature is "0 0 -25%".  I think the percentage value doesn't work well with the really long and really short content sections.  Changing this to fixed value (-48px) seems to help.

Issue #244 - Changing the rootMargin offset to -48px top/bottom.

---

components/contact_card/README.md
components/contact_card/contact_card.component.yml
components/contact_card/contact_card.scss
components/contact_card/contact_card.twig
psulib_base.theme

Refactoring the contact_card component to allow us to pass render arrays for contact information.  This change will likely cause issues with any current implementation of the contact_card (e.g. node--department--contact.html.twig, and node--library-contact.html.twig).
The contact display for departments should be
```twig
{% embed 'psulib_base:contact_card' with {
title: label,
title_url: url,
subtitle: '',
address: content.field_psofficeaddress,
website: '',
stacked: true,
linked_card: true,
} %}
{% block email %}{{ content.field_email }}{% endblock %}
{% block phones %}{{ content.field_general_phone }}{% endblock %}
{% block fax %}{{ content.field_fax_number }}{% endblock %}
{% endembed %}
```

237 add directory display variant to contact card fixes

---

components/contact_card/README.md
components/contact_card/contact_card.component.yml
components/contact_card/contact_card.scss
components/contact_card/contact_card.twig
package-lock.json

Renamed the slots since those are the new items (appending `_block` to the slot name).  See the readme for updated instructions on how to use this.

237 add directory display variant to contact card bugs

---

templates/block/block--system-menu-block.html.twig

This can be tested on https://hershey.psul.localhost/ (need to clear cache).  There should be no blocks with id of `-menu`

Issue #277 - Adding default id to block menu template.

---

components/button/button.example.html
components/button/button.scss
components/header/header.scss
components/header_mark/header_mark.twig
package-lock.json
scss/_variables_bootstrap.scss

This is sort of a biggie.  I tried to sync the PSU Flex and Bootstrap button styles.  
- Buttons should have a small radius by default now.
- The primary button style should be pa-link color
- There are new styles for making `Report` and `Navlink` buttons
- Copy html content from button.example.html file into a new node.  You should see button styles similar to those in [Figma Button Styles](https://www.figma.com/design/QUWCtZma6OvgSVhnwobLZ0/Styles?node-id=3261-1185&t=175oGkjuPKqcLmh3-0)
- Spot check sites for impacts.
- The PSUL Homepage search and header search blocks will need to be updated

276 improve buttons

---

components/divider/divider.component.yml
components/divider/divider.scss
components/divider/divider.twig
components/heading/heading.component.yml
components/heading/heading.twig
components/not_found/not_found.scss
components/not_found/not_found.twig
package-lock.json

Adding a divider component.  This is currently only being used on the 404 and 403 pages but you can use those to play around with component. 
- Go to https://psul-web.psul.localhost/thisisnotapagelolololol
- You should see divider bar is displayed below the H1.
- You can tweak the settings in `web/themes/custom/psulib_base/components/not_found/not_found.twig` to see how this work. The available props are in the divider component.

283 component divider

---

components/accordion/accordion.scss

add an accordion via ckeditor. the accordion header items should not have underlines.

292-remove underline from ckeditor_bs_accordion button

---

components/divider/divider.component.yml
components/divider/divider.scss
components/image_text_overlap/README.md
components/image_text_overlap/image_text_overlap.component.yml
components/image_text_overlap/image_text_overlap.scss
components/image_text_overlap/image_text_overlap.twig
scss/_mixins.scss
scss/base/_full_bleed.scss

Adding a new component.
You can add the following to a twig template (could be `page.html.twig` or `page--front.html.twig`).  This should behave like the Image + Text Overlap component on the psu.edu homepage.
```twig
<div class="full-bleed full-bleed--limestone-light">
{%
include 'psulib_base:image_text_overlap' with {
image_src: 'https://images.ctfassets.net/ni9rh5nu0d99/7aVwroYXl3CQkyfQwEK1bG/999f75fe46e3cbbd2bea829866abe21a/traditions-lion-shrine.jpg?fm=webp&w=640&q=75',
title: 'Celebrating Pride and Connection',
body: {'#markup': '<p>We are proud to be a part of the Penn State community and to support our <a href="#">students, faculty, and staff</a> in their academic pursuits. We are committed to creating an inclusive environment that celebrates diversity and fosters …
```

282 component image text overlap

---

demos/peripheral-bootstrap3.html
demos/peripheral-sidebar.html
demos/peripheral.html
package-lock.json
scss/base/_google_fonts.scss
scss/peripheral-bootstrap3.scss
scss/peripheral.scss
webpack.mix.js

The intention of the bootstrap3 css library is to allow us to update the styles on LibApps since our Bootstrap5 styles are causing issues.
- Added a peripheral css file that will hopefully work with bootstrap3 based services.
- Added 3 demo pages to show case 
- Update existing peripheral to:
- Include header, footer, and sidebar styles 
- Fixing a few style issues
- Added styles (full-bleed, divider)
- Use CDN for bootstrap icons and fonts
- Removed fonts assets and bootstrap icons files from build.
The demo pages should.  Note the bootstrap-3 heading and behaviors are different since there is no off canvas component. 
- https://psul-web.psul.localhost/themes/custom/psulib_base/demos/peripheral.html
- https://psul-web.psul.localhost/themes/custom/psulib_base/demos/peripheral-sidebar.html …

279 peripherals improvement

---

layouts/psul-one-column.html.twig
package-lock.json
psulib_base.theme
scss/base/_layout.scss
scss/base/_typography.scss
templates/layout/page--node--lb-display.html.twig

This requires layout builder to work.  I can checkout https://github.com/psu-libraries/psul-web/pull/911 in psul-web
- Adds template for nodes using layout builder (and theme suggestions so this can be overridden)
- Adjust styles to make spacing more consistent around sections and layout pages.
- Create a Landing page
- Update the layout (Add sections and text blocks).
- Spacing should be consistent.

325 add template for landing page

---

.storybook/preview.js
components/library_search/library_search.component.yml
components/library_search/library_search.scss
components/library_search/library_search.twig
components/pagination/pagination.component.yml
scss/base/_full_bleed.scss
stories/psul-homepage.stories.js

A mock up the desktop display of the library component can be found [in Figma](https://www.figma.com/design/BxEdRfr8AFa5bG0DYOVzcF/PSUL-Header-Mockups?node-id=864-249&t=9Sc4xwiygFCKh3BC-0).
- Go to http://localhost:6006/?path=/story/sdc-library-search--basic
- You should the search form component form.  This should look ok on all screen sizes (any feedback is appreciated)
- Go to http://localhost:6006/?path=/story/psu-libraries-homepage--basic
- The full-bleed styles should look ok.
- You should the search form component form.  This should look ok on all screen sizes (any feedback is appreciated)
- Go to https://psul-web.psul.localhost/directory?search=&expertise=All&campus=beaver&library=All&department=All
- The full-bleed styles should look ok. The page should load (fixing #341)

339 add library search component

---

.storybook/preview.js
components/heading/heading.component.yml
components/heading/heading.twig

Minor change.  This allow target attribute to be added to headings with links.
- Go to http://localhost:6006/?path=/story/sdc-heading--basic
- Set title_link to "https://psu.edu"
- Set the heading_link_target to "_blank"
- View source.
- You should see the heading is a link with a target attribute of _blank.
- Changing the target value will be reflected in the story.

Issue #343 - Adding link target prop to heading component.

---

layouts/psul-two-column.html.twig
psulib_base.layouts.yml
psulib_base.theme
templates/navigation/menu--main--nav-main.html.twig

- Added new layout that mirrors page layout (with one column with gray background).  
- Added hook to remove default layouts
- Updated the main menu templates to use sidebar menu layout by default (instead of header menu).
- Checkout https://github.com/psu-libraries/psul-web/pull/937 on psul-web (and deploy changes)
- Clear cache
- Add or Edit a landing page layout
- Add section
- You should see 5 sections include the layout (default layout builder styles should not displayed only psulib_base layouts should be visible).
- Add "Two column 350px sidebar"
- Add menu block to the side bar of layout (see image below for settings)
- Add content to the main section of layout
- You should see a layout like that above

348 add 2 column layout that mirror standard node layout

---

templates/form/details.html.twig

- add a Details field in webform with no custom classes. it should look correct.
- edit the field, go to `Summary attributes`. in `Summary CSS classes` field, enter `bg-info`. you should see the background color is changed to light blue

421-remove bg-light from webform details template
